// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwgaLYmF7bGxhb77CNuAfUCE5manlirI',
    appId: '1:718208993218:web:39ba6089daad00e666385b',
    messagingSenderId: '718208993218',
    projectId: 'tp-smartkart-7dc93',
    authDomain: 'tp-smartkart-7dc93.firebaseapp.com',
    storageBucket: 'tp-smartkart-7dc93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5URP4wMjePelwCAu3qcToUDaasM0ezY',
    appId: '1:718208993218:android:a32faf3c11bf84ae66385b',
    messagingSenderId: '718208993218',
    projectId: 'tp-smartkart-7dc93',
    storageBucket: 'tp-smartkart-7dc93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyd80NiS-a2iNq5jl92tc8oKignTd5Vg',
    appId: '1:718208993218:ios:15c703ee6c09abf566385b',
    messagingSenderId: '718208993218',
    projectId: 'tp-smartkart-7dc93',
    storageBucket: 'tp-smartkart-7dc93.appspot.com',
    iosBundleId: 'com.example.smartCarts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyd80NiS-a2iNq5jl92tc8oKignTd5Vg',
    appId: '1:718208993218:ios:15c703ee6c09abf566385b',
    messagingSenderId: '718208993218',
    projectId: 'tp-smartkart-7dc93',
    storageBucket: 'tp-smartkart-7dc93.appspot.com',
    iosBundleId: 'com.example.smartCarts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwgaLYmF7bGxhb77CNuAfUCE5manlirI',
    appId: '1:718208993218:web:64230562c60eb03666385b',
    messagingSenderId: '718208993218',
    projectId: 'tp-smartkart-7dc93',
    authDomain: 'tp-smartkart-7dc93.firebaseapp.com',
    storageBucket: 'tp-smartkart-7dc93.appspot.com',
  );

}